{"uuid": "bdeb3386-b42f-4474-ac97-9048658a46ce", "children": ["1a810213-7079-4cbd-94cc-f7e2559ffd61"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=132.0.6834.196)\nStacktrace:\n\tGetHandleVerifier [0x00007FF729726CF5+28821]\n\t(No symbol) [0x00007FF729693880]\n\t(No symbol) [0x00007FF72953578A]\n\t(No symbol) [0x00007FF729532E88]\n\t(No symbol) [0x00007FF729523BF9]\n\t(No symbol) [0x00007FF72952594F]\n\t(No symbol) [0x00007FF729523EBF]\n\t(No symbol) [0x00007FF72952371B]\n\t(No symbol) [0x00007FF72952365A]\n\t(No symbol) [0x00007FF729521274]\n\t(No symbol) [0x00007FF729521B3C]\n\t(No symbol) [0x00007FF72953885A]\n\t(No symbol) [0x00007FF7295D01FE]\n\t(No symbol) [0x00007FF7295AF2FA]\n\t(No symbol) [0x00007FF7295CF412]\n\t(No symbol) [0x00007FF7295AF0A3]\n\t(No symbol) [0x00007FF72957A778]\n\t(No symbol) [0x00007FF72957B8E1]\n\tGetHandleVerifier [0x00007FF729A5FCED+3408013]\n\tGetHandleVerifier [0x00007FF729A7745F+3504127]\n\tGetHandleVerifier [0x00007FF729A6B63D+3455453]\n\tGetHandleVerifier [0x00007FF7297EBDFB+835995]\n\t(No symbol) [0x00007FF72969EB9F]\n\t(No symbol) [0x00007FF72969A854]\n\t(No symbol) [0x00007FF72969A9ED]\n\t(No symbol) [0x00007FF72968A1D9]\n\tBaseThreadInitThunk [0x00007FFAEB4A7374+20]\n\tRtlUserThreadStart [0x00007FFAEC57CC91+33]\n\n", "trace": "  File \"C:\\Users\\Kirill Troitsky\\practicum\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Kirill Troitsky\\practicum\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Kirill Troitsky\\practicum\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Kirill Troitsky\\practicum\\Diplom\\Diplom_3\\tests\\conftest.py\", line 16, in driver\n    driver.get(main_site)\n  File \"C:\\Users\\Kirill Troitsky\\practicum\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Kirill Troitsky\\practicum\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Kirill Troitsky\\practicum\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739721771420, "stop": 1739721774907}], "start": 1739721771420, "stop": 1739721774939}